version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j0w8u321sqyg"
s3_prefix = "sam-app2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
